-- 用有授权能力的数据库账号执行一次。
-- 如果应用数据库用户不是 BASIC$holo_r，请替换下面的用户名。

GRANT USAGE ON SCHEMA knowledge TO "BASIC$holo_r";

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA knowledge
TO "BASIC$holo_r";

GRANT USAGE, SELECT, UPDATE
ON ALL SEQUENCES IN SCHEMA knowledge
TO "BASIC$holo_r";

ALTER DEFAULT PRIVILEGES IN SCHEMA knowledge
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "BASIC$holo_r";

ALTER DEFAULT PRIVILEGES IN SCHEMA knowledge
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO "BASIC$holo_r";
