-- 可选：从 bi.dim_org_admin_user_info_hf 同步账号资料到 knowledge.app_user
-- 默认假设源表提供 password_hash；如果源表列名不同，请按实际字段名调整，或直接使用应用内的自动同步逻辑。

INSERT INTO knowledge.app_user (
    admin_id,
    mobile,
    status,
    user_name,
    we_user_id,
    role_id,
    employee_id,
    admin_organ_id,
    organ_name,
    teacher_uid,
    subject,
    role_name,
    is_full_view,
    permission_type,
    permission_scope,
    admin_organ_ids,
    parent_ids,
    password_hash,
    source_create_date,
    source_update_date,
    created_at,
    updated_at
)
SELECT
    admin_id,
    mobile,
    status,
    user_name,
    we_user_id,
    role_id,
    employee_id,
    admin_organ_id,
    organ_name,
    teacher_uid,
    subject,
    role_name,
    is_full_view,
    permission_type,
    permission_scope,
    admin_organ_ids,
    parent_ids,
    password_hash,
    create_date,
    update_date,
    NOW(),
    NOW()
FROM bi.dim_org_admin_user_info_hf
WHERE admin_id IS NOT NULL
ON CONFLICT (admin_id) DO UPDATE SET
    mobile = EXCLUDED.mobile,
    status = EXCLUDED.status,
    user_name = EXCLUDED.user_name,
    we_user_id = EXCLUDED.we_user_id,
    role_id = EXCLUDED.role_id,
    employee_id = EXCLUDED.employee_id,
    admin_organ_id = EXCLUDED.admin_organ_id,
    organ_name = EXCLUDED.organ_name,
    teacher_uid = EXCLUDED.teacher_uid,
    subject = EXCLUDED.subject,
    role_name = EXCLUDED.role_name,
    is_full_view = EXCLUDED.is_full_view,
    permission_type = EXCLUDED.permission_type,
    permission_scope = EXCLUDED.permission_scope,
    admin_organ_ids = EXCLUDED.admin_organ_ids,
    parent_ids = EXCLUDED.parent_ids,
    password_hash = EXCLUDED.password_hash,
    source_create_date = EXCLUDED.source_create_date,
    source_update_date = EXCLUDED.source_update_date,
    updated_at = NOW();
